/**
 * E2E WebAuthn helper — Playwright virtual authenticator for passkey tests.
 *
 * Playwright 1.61 introduced `browserContext.credentials` — a virtual WebAuthn
 * authenticator that intercepts `navigator.credentials.create()` and
 * `navigator.credentials.get()` via an injected script + binding. It works on
 * Chromium, Firefox, and WebKit with no hardware, no OS prompt, no real
 * security key.
 *
 * The BE proxies Casdoor's WebAuthn endpoints. Casdoor's `app.conf` has
 * `origin =` (empty), so it derives the WebAuthn RPOrigin from the request
 * `Host` header. The BE sends `Host: <browser-host>` (e.g. `localhost:5173`)
 * via `hostOverride` in `fetchWithHost()`. Therefore:
 *   - rpId = `localhost`
 *   - RPOrigin = `http://localhost:5173`
 *
 * The virtual authenticator must seed passkeys with `rpId: 'localhost'` so the
 * signed assertion matches what Casdoor expects.
 *
 * Docs: https://playwright.dev/docs/api/class-credentials
 * PR:    https://github.com/microsoft/playwright/pull/40849
 */
import { promises as fs } from "node:fs";
import { join } from "node:path";
import type { BrowserContext } from "@playwright/test";

/** The rpId used by the virtual authenticator. Must match the BE/Casdoor derivation. */
export const WEBAUTHN_RP_ID = "localhost";

/** Directory where captured passkey credentials are saved between tests. */
export const AUTH_DIR = join(process.cwd(), "playwright", ".auth");
export const PASSKEY_FILE = join(AUTH_DIR, "passkey.json");

export interface CapturedPasskey {
  rpId: string;
  id: string; // base64url
  userHandle?: string; // base64url
  privateKey: string; // base64url PKCS#8 (DER)
  publicKey: string; // base64url SPKI (DER)
}

/**
 * Install the virtual authenticator on a browser context and seed a fresh
 * passkey for `localhost`. The passkey is generated by Playwright (ECDSA P-256).
 *
 * Call this BEFORE navigating to a page that will trigger
 * `navigator.credentials.create()` or `navigator.credentials.get()`.
 *
 * @returns The seeded passkey credential (so the caller can save it for reuse).
 */
export async function installVirtualAuthenticator(
  context: BrowserContext,
): Promise<CapturedPasskey> {
  // Create a fresh passkey for the rpId. Playwright generates the keypair
  // (ECDSA P-256) and returns the credential (id, privateKey, publicKey).
  const credential = await context.credentials.create(WEBAUTHN_RP_ID);
  // Install the interceptor — from now on, navigator.credentials.get/create
  // in any page in this context are answered by the virtual authenticator.
  await context.credentials.install();
  return credential as unknown as CapturedPasskey;
}

/**
 * Install the virtual authenticator on a browser context AND seed a previously
 * captured passkey (loaded from disk). Use this when a test needs to sign in
 * with a passkey that was enrolled in a previous test run.
 */
export async function installVirtualAuthenticatorWithPasskey(
  context: BrowserContext,
  passkey: CapturedPasskey,
): Promise<void> {
  // Re-seed the saved credential (with its private key) into the authenticator.
  await context.credentials.create(passkey.rpId, {
    id: passkey.id,
    userHandle: passkey.userHandle,
    privateKey: passkey.privateKey,
    publicKey: passkey.publicKey,
  });
  await context.credentials.install();
}

/**
 * After a `navigator.credentials.create()` ceremony (passkey enrollment) has
 * run on the page, read back the captured passkey from the virtual
 * authenticator. The captured credential includes the private key, so it can
 * be saved to disk and reused in later test runs for `navigator.credentials.get()`.
 *
 * @returns The first captured passkey for the rpId, or null if none.
 */
export async function captureEnrolledPasskey(
  context: BrowserContext,
): Promise<CapturedPasskey | null> {
  const credentials = await context.credentials.get({ rpId: WEBAUTHN_RP_ID });
  if (credentials.length === 0) return null;
  return credentials[0] as unknown as CapturedPasskey;
}

/**
 * Save a captured passkey to `playwright/.auth/passkey.json` so it can be
 * loaded by a later test run. The `.auth` directory is gitignored.
 */
export async function savePasskey(passkey: CapturedPasskey): Promise<void> {
  await fs.mkdir(AUTH_DIR, { recursive: true });
  await fs.writeFile(PASSKEY_FILE, JSON.stringify(passkey, null, 2), "utf-8");
}

/**
 * Load a previously saved passkey from `playwright/.auth/passkey.json`.
 * @returns The passkey, or null if the file does not exist (first run).
 */
export async function loadPasskey(): Promise<CapturedPasskey | null> {
  try {
    const content = await fs.readFile(PASSKEY_FILE, "utf-8");
    return JSON.parse(content) as CapturedPasskey;
  } catch {
    return null;
  }
}

/**
 * Delete the saved passkey file. Called during cleanup after Suite B.
 */
export async function deletePasskeyFile(): Promise<void> {
  try {
    await fs.unlink(PASSKEY_FILE);
  } catch {
    // File may not exist on a fresh run — ignore.
  }
}

/**
 * Delete all seeded credentials for the rpId from the virtual authenticator.
 * Useful for cleanup between tests in the same context.
 */
export async function clearVirtualAuthenticator(
  context: BrowserContext,
): Promise<void> {
  const credentials = await context.credentials.get({ rpId: WEBAUTHN_RP_ID });
  for (const cred of credentials) {
    await context.credentials.delete(cred.id);
  }
}
